version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - main
skip_tags: true
image: Visual Studio 2022
configuration: Release
platform: x64
build:
  project: GFNWindowMover.csproj
  verbosity: normal
skip_commits:
  files:
  - '*.md'
  - '*.png'
  - LICENSE
  - '.gitignore'
  - 'App.config'
  - 'appveyor.yml'
