version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - main
skip_tags: true
image: Visual Studio 2022
configuration: Release
platform: x64
build:
  project: GeForceNowWindowMover.csproj
  verbosity: normal
after_build:
- cmd: 7z a GeForceNow_WindowMover.zip %APPVEYOR_BUILD_FOLDER%\Release\*.exe %APPVEYOR_BUILD_FOLDER%\Release\*.exe.config
artifacts:
- path: GeForceNow_WindowMover.zip
  name: deploy
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: GeforceNowWindowMover-v$(appveyor_build_version)
  auth_token:
    secure: Jib02JvY9eExnO/sKNidWw8d5URXJ2xl7jY1iJXYqVWlAwwaBMHkNA+mHslpIjjJ
  artifact: deploy
  draft: false
  prerelease: true
  force_update: true
  on:
    branch: main
skip_commits:
  files:
  - '*.md'
  - LICENSE
  - '.gitignore'
  - 'App.config'
