//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeForceNowWindowMover {
    using System;
    
    
    /// <summary>
    /// Eine streng typisierte Resourcenklasse, zum Suchen nach lokalisierten Zeichenfolgen und entsprechenden Formatfunktionen.
    /// </summary>
    // Die Klasse wird automatisch von StronglyTypedResourceBuilderEx mittels dem ResXFileCodeGeneratorEx Werkzeug generiert.
    // Zum Hinzufügen oder Löschen eines Members, ändern Sie die .ResX-Datei. Danach führen Sie das ResXFileCodeGeneratorEx Werkzeug aus oder Kompilieren Ihr VS.NET Projekt.
    // Copyright (c) Dmytro Kryvko 2006-2022 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "2.6.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class frmMessure {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initalisiert ein frmMessure-Objekt.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public frmMessure() {
        }
        
        /// <summary>
        /// Thread safe lock Objekt, die von dieser Klasse verwendet wird.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Gibt einen gespeicherte Instanz des ResourceManager zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("GeForceNowWindowMover.frmMessure", typeof(frmMessure).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Überschreibt die aktuelle CurrentUICulture des Threads für Alles
        /// Resource durchsucht die streng typisierte Resourcenklasse.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Sucht eine Resource 'btnCancel.Anchor'.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles btnCancel_Anchor {
            get {
                return ((System.Windows.Forms.AnchorStyles)(ResourceManager.GetObject(frmMessure.ResourceNames.btnCancel_Anchor, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Sucht eine Resource 'btnCancel.Font'.
        /// </summary>
        public static System.Drawing.Font btnCancel_Font {
            get {
                return ((System.Drawing.Font)(ResourceManager.GetObject(frmMessure.ResourceNames.btnCancel_Font, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Sucht eine Resource 'btnCancel.Location'.
        /// </summary>
        public static System.Drawing.Point btnCancel_Location {
            get {
                return ((System.Drawing.Point)(ResourceManager.GetObject(frmMessure.ResourceNames.btnCancel_Location, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Sucht eine Resource 'btnCancel.Size'.
        /// </summary>
        public static System.Drawing.Size btnCancel_Size {
            get {
                return ((System.Drawing.Size)(ResourceManager.GetObject(frmMessure.ResourceNames.btnCancel_Size, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Sucht eine Resource 'btnCancel.TabIndex'.
        /// </summary>
        public static int btnCancel_TabIndex {
            get {
                return ((int)(ResourceManager.GetObject(frmMessure.ResourceNames.btnCancel_TabIndex, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die 'CANCEL' ähnelt.
        /// </summary>
        public static string btnCancel_Text {
            get {
                return ResourceManager.GetString(frmMessure.ResourceNames.btnCancel_Text, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Sucht eine Resource 'btnOk.Anchor'.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles btnOk_Anchor {
            get {
                return ((System.Windows.Forms.AnchorStyles)(ResourceManager.GetObject(frmMessure.ResourceNames.btnOk_Anchor, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Sucht eine Resource 'btnOk.Font'.
        /// </summary>
        public static System.Drawing.Font btnOk_Font {
            get {
                return ((System.Drawing.Font)(ResourceManager.GetObject(frmMessure.ResourceNames.btnOk_Font, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Sucht eine Resource 'btnOk.Location'.
        /// </summary>
        public static System.Drawing.Point btnOk_Location {
            get {
                return ((System.Drawing.Point)(ResourceManager.GetObject(frmMessure.ResourceNames.btnOk_Location, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Sucht eine Resource 'btnOk.Size'.
        /// </summary>
        public static System.Drawing.Size btnOk_Size {
            get {
                return ((System.Drawing.Size)(ResourceManager.GetObject(frmMessure.ResourceNames.btnOk_Size, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Sucht eine Resource 'btnOk.TabIndex'.
        /// </summary>
        public static int btnOk_TabIndex {
            get {
                return ((int)(ResourceManager.GetObject(frmMessure.ResourceNames.btnOk_TabIndex, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die 'SAVE' ähnelt.
        /// </summary>
        public static string btnOk_Text {
            get {
                return ResourceManager.GetString(frmMessure.ResourceNames.btnOk_Text, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Sucht eine Resource 'label1.Anchor'.
        /// </summary>
        public static System.Windows.Forms.AnchorStyles label1_Anchor {
            get {
                return ((System.Windows.Forms.AnchorStyles)(ResourceManager.GetObject(frmMessure.ResourceNames.label1_Anchor, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Sucht eine Resource 'label1.Font'.
        /// </summary>
        public static System.Drawing.Font label1_Font {
            get {
                return ((System.Drawing.Font)(ResourceManager.GetObject(frmMessure.ResourceNames.label1_Font, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Sucht eine Resource 'label1.Location'.
        /// </summary>
        public static System.Drawing.Point label1_Location {
            get {
                return ((System.Drawing.Point)(ResourceManager.GetObject(frmMessure.ResourceNames.label1_Location, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Sucht eine Resource 'label1.Size'.
        /// </summary>
        public static System.Drawing.Size label1_Size {
            get {
                return ((System.Drawing.Size)(ResourceManager.GetObject(frmMessure.ResourceNames.label1_Size, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Sucht eine Resource 'label1.TabIndex'.
        /// </summary>
        public static int label1_TabIndex {
            get {
                return ((int)(ResourceManager.GetObject(frmMessure.ResourceNames.label1_TabIndex, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die 'Move and Resize the form to the desired position and size for GeForce Now Window' ähnelt.
        /// </summary>
        public static string label1_Text {
            get {
                return ResourceManager.GetString(frmMessure.ResourceNames.label1_Text, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Sucht eine Resource 'label1.TextAlign'.
        /// </summary>
        public static System.Drawing.ContentAlignment label1_TextAlign {
            get {
                return ((System.Drawing.ContentAlignment)(ResourceManager.GetObject(frmMessure.ResourceNames.label1_TextAlign, _resourceCulture)));
            }
        }
        
        /// <summary>
        /// Liste aller Resourcenbezeichnungen als konstante String Felder
        /// </summary>
        internal class ResourceNames {
            
            /// <summary>
            /// Speichert die Resourcenbezeichnung 'btnCancel.Anchor'.
            /// </summary>
            public const string btnCancel_Anchor = "btnCancel.Anchor";
            
            /// <summary>
            /// Speichert die Resourcenbezeichnung 'btnCancel.Font'.
            /// </summary>
            public const string btnCancel_Font = "btnCancel.Font";
            
            /// <summary>
            /// Speichert die Resourcenbezeichnung 'btnCancel.Location'.
            /// </summary>
            public const string btnCancel_Location = "btnCancel.Location";
            
            /// <summary>
            /// Speichert die Resourcenbezeichnung 'btnCancel.Size'.
            /// </summary>
            public const string btnCancel_Size = "btnCancel.Size";
            
            /// <summary>
            /// Speichert die Resourcenbezeichnung 'btnCancel.TabIndex'.
            /// </summary>
            public const string btnCancel_TabIndex = "btnCancel.TabIndex";
            
            /// <summary>
            /// Speichert die Resourcenbezeichnung 'btnCancel.Text'.
            /// </summary>
            public const string btnCancel_Text = "btnCancel.Text";
            
            /// <summary>
            /// Speichert die Resourcenbezeichnung 'btnOk.Anchor'.
            /// </summary>
            public const string btnOk_Anchor = "btnOk.Anchor";
            
            /// <summary>
            /// Speichert die Resourcenbezeichnung 'btnOk.Font'.
            /// </summary>
            public const string btnOk_Font = "btnOk.Font";
            
            /// <summary>
            /// Speichert die Resourcenbezeichnung 'btnOk.Location'.
            /// </summary>
            public const string btnOk_Location = "btnOk.Location";
            
            /// <summary>
            /// Speichert die Resourcenbezeichnung 'btnOk.Size'.
            /// </summary>
            public const string btnOk_Size = "btnOk.Size";
            
            /// <summary>
            /// Speichert die Resourcenbezeichnung 'btnOk.TabIndex'.
            /// </summary>
            public const string btnOk_TabIndex = "btnOk.TabIndex";
            
            /// <summary>
            /// Speichert die Resourcenbezeichnung 'btnOk.Text'.
            /// </summary>
            public const string btnOk_Text = "btnOk.Text";
            
            /// <summary>
            /// Speichert die Resourcenbezeichnung 'label1.Anchor'.
            /// </summary>
            public const string label1_Anchor = "label1.Anchor";
            
            /// <summary>
            /// Speichert die Resourcenbezeichnung 'label1.Font'.
            /// </summary>
            public const string label1_Font = "label1.Font";
            
            /// <summary>
            /// Speichert die Resourcenbezeichnung 'label1.Location'.
            /// </summary>
            public const string label1_Location = "label1.Location";
            
            /// <summary>
            /// Speichert die Resourcenbezeichnung 'label1.Size'.
            /// </summary>
            public const string label1_Size = "label1.Size";
            
            /// <summary>
            /// Speichert die Resourcenbezeichnung 'label1.TabIndex'.
            /// </summary>
            public const string label1_TabIndex = "label1.TabIndex";
            
            /// <summary>
            /// Speichert die Resourcenbezeichnung 'label1.Text'.
            /// </summary>
            public const string label1_Text = "label1.Text";
            
            /// <summary>
            /// Speichert die Resourcenbezeichnung 'label1.TextAlign'.
            /// </summary>
            public const string label1_TextAlign = "label1.TextAlign";
        }
    }
}
