name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore .\GeForceNowWindowMover.sln

      - name: Build
        run: dotnet build .\GeForceNowWindowMover.sln -c Release --no-restore

      - name: Test
        run: dotnet test .\GFNWindowMover.Tests\GFNWindowMover.Tests.csproj -c Release --no-build --verbosity normal
